### ISSUE TITLE
Add details of WWC to website

### ISSUE THREAD

**Issue by elfgoh** [geekcampsg/website#100]
Women who code will have a workshop running concurrently at GeekcampSG. We should mention some details

Section name: ML Track
Text: GeekcampSG has partnered with [Women Who Code Singapore](https://www.meetup.com/Women-Who-Code-Singapore/) to have their [Machines Learning and Edge Computing Workshop](https://www.meetup.com/Women-Who-Code-Singapore/events/264579891/) as a concurrent track during the first half of the conference. Do RSVP at the [meetup.com event page](https://www.meetup.com/Women-Who-Code-Singapore/events/264579891/) and bring your laptop for this workshop. This will be held at Cardamom, Lvl 2 of Shaw Foundation Alumni House.

**Comment by arynchoong** [comment]
Please take care to use Women Who Code or WWCode when mentioning us. Otherwise, it looks good. Thanks

**Comment by elfgoh** [comment]
> Please take care to use Women Who Code or WWCode when mentioning us. Otherwise, it looks good. Thanks

@arynchoong 

- `Women Who Code Singapore`, changed to `Women Who Code`
- Appended `All are welcomed!`

Text: GeekcampSG has partnered with [Women Who Code](https://www.meetup.com/Women-Who-Code-Singapore/) to have their [Machines Learning and Edge Computing Workshop](https://www.meetup.com/Women-Who-Code-Singapore/events/264579891/) as a concurrent track during the first half of the conference. Do RSVP at the [meetup.com event page](https://www.meetup.com/Women-Who-Code-Singapore/events/264579891/) and bring your laptop for this workshop. This will be held at Cardamom, Lvl 2 of Shaw Foundation Alumni House. All are welcomed!

**Comment by arynchoong** [comment]
Women Who Code Singapore is ok, but can help change the link to : https://www.womenwhocode.com/singapore
Thanks!

**Comment by elfgoh** [comment]
> Women Who Code Singapore is ok, but can help change the link to : https://www.womenwhocode.com/singapore
> Thanks!

Changed: 

Text: GeekcampSG has partnered with [Women Who Code Singapore](https://www.womenwhocode.com/singapore) to have their [Machines Learning and Edge Computing Workshop](https://www.meetup.com/Women-Who-Code-Singapore/events/264579891/) as a concurrent track during the first half of the conference. Do RSVP at the [meetup.com event page](https://www.meetup.com/Women-Who-Code-Singapore/events/264579891/) and bring your laptop for this workshop. This will be held at Cardamom, Lvl 2 of Shaw Foundation Alumni House. All are welcomed!

**Comment by SheldonCheng** [comment]
Done. https://github.com/GeekcampSG/geekcampsg.github.io/pull/105
