### ISSUE TITLE
Add partner logos

### ISSUE THREAD

**Issue by elfgoh** [geekcampsg/website#101]
- [ ] [NUS Hackers](https://www.nushackers.org/): Logo emailed
- [ ] [12Geeks](https://12geeks.com/community/): Logo emailed
- [ ] Junction x Singapore: Logo in chat
- [ ] [Engineers.sg](https://engineers.sg/)
- [ ] [Women Who Code Singapore](https://www.womenwhocode.com/singapore): Logo emailed
- [ ] [OSI Layer 8](https://osilayer8.makerforce.io/): [Logo](https://github.com/GeekcampSG/geekcampsg.github.io/issues/94#issuecomment-538389657)

**Comment by SheldonCheng** [comment]
Done https://github.com/GeekcampSG/geekcampsg.github.io/pull/106
