### ISSUE TITLE
Abstract event schedule into JSON

### ISSUE THREAD

**Issue by stanleynguyen** [geekcampsg/website#134]
This schedule
https://github.com/GeekcampSG/geekcampsg.github.io/blob/a44fd60c7d95ef7ab8fc273307289b64ad5b4218/src/sections/3.schedule.js#L18-L175
could be abstracted into JSON data and (optional) stored in a separate data file for ease of editing and more readability

**Comment by tanhauhau** [comment]
this is now stored in JSON
