### ISSUE TITLE
[CONF-2022]  add organisers section

### ISSUE THREAD

**Issue by perwyl** [geekcampsg/website#178]
- add organiser info

**Comment by hongkheng** [comment]
i think not high priority

**Comment by elfgoh** [comment]
> i think not high priority

I disagree. I think let's try to give a bit more recognition to volunteers

**Comment by hongkheng** [comment]
Will need to come out with some design and ideas.

**Comment by hongkheng** [comment]
@elfgoh & @perwyl I need a list of all the volunteers. So that I can update this file https://github.com/GeekcampSG/geekcampsg.github.io/blob/master/src/data/committee2021.js or shift it to a json file.

**Comment by vinamelody** [comment]
will take this one :)
