### ISSUE TITLE
[Community partner 2022] RubySG

### ISSUE THREAD

**Issue by elfgoh** [geekcampsg/website#188]
https://ruby.sg/
https://ruby.sg/assets/ruby-sg-logo-d0f9ecab507a3af8a2376ba1be73cfc7132037eca6f0a1785d6f8f7fc2f6800d.png

**Comment by TayKangSheng** [comment]
Logo (its white with transparent background!)
* <kbd>![ruby-sg-logo](https://user-images.githubusercontent.com/10722197/190840852-9c366774-a5bd-4bfd-9873-02c5ae4519fe.png)</kbd>

Banner
* <kbd>![rubysg-banner (1)](https://user-images.githubusercontent.com/10722197/190840846-9eca022d-0811-40dd-af9a-34fdd354694b.png)</kbd>
