### ISSUE TITLE
[CONF-2022] refresh section what people says

### ISSUE THREAD

**Issue by perwyl** [geekcampsg/website#191]

**Comment by elfgoh** [comment]
Why ah?

**Comment by perwyl** [comment]
> Why ah?

it has been there for very long, i feel it's time to update the info. you feel otherwise?

**Comment by elfgoh** [comment]
I feel we can give an update if there are new quotes. Otherwise it can stay unless there are other compelling reasons such as too cluttered or conflicts with design, etc

**Comment by hongkheng** [comment]
I feel we can update the quotes and re-generate the ascii pictures. Can be worth doing if we want update this. I think we should add some animations to the website.

**Comment by elfgoh** [comment]
> I feel we can update the quotes and re-generate the ascii pictures. Can be worth doing if we want update this. I think we should add some animations to the website.

If we wanna update, here are 3 tweets which could be possible updates

- https://twitter.com/subhransu/status/1562416772866707456
- https://twitter.com/Knguyentrieu/status/1185475318858928129
- https://twitter.com/wgx731/status/1185354142803361792
