### ISSUE TITLE
[CONF-2022] Add venue sponsor SP Digital 

### ISSUE THREAD

**Issue by elfgoh** [geekcampsg/website#194]
![logo-spdigital-rgb-03-landscape-01B-fullcolor-dark](https://user-images.githubusercontent.com/491688/194342989-86caaeb9-bcbc-457c-a9f1-752047858176.png)
![logo-spdigital-rgb-02-portrait-01A-fullcolor-dark](https://user-images.githubusercontent.com/491688/194343005-85ddb488-8e40-4b78-9c1b-6ed91489f618.png)

@tanhauhau @perwyl @serverwentdown possible to expedite this?

**Comment by elfgoh** [comment]
Choose one. Since we do not have that many sponsors, possible to use the first one?

**Comment by MisterDoobDoob** [comment]
Is there a specific URL to use? If not I'll default to https://www.spdigital.sg/

**Comment by elfgoh** [comment]
> Is there a specific URL to use? If not I'll default to https://www.spdigital.sg/

That will work thanks!

**Comment by MisterDoobDoob** [comment]
Sorry no, realised I put it to https://www.spdigital.sg/about-us.html instead
