### ISSUE TITLE
fix color balance for picture of Melvin Zhang

### ISSUE THREAD

**Issue by melvinzhang** [geekcampsg/website#78]
I tried my best to get rid of the picture with the wrong color balance but seems that there are still a few out there...

Attached is a corrected version of the image with fixed color balance.

Update: removed attachment as correction didn't work out...

**Comment by melvinzhang** [comment]
Hmm, looks like my gimp-fu is quite terrible and it still looks a bit strange. This is the one I passed to Luther, the colors look more correct but the ratio is different. Please use this instead. Thanks!

![melvinz](https://user-images.githubusercontent.com/1620634/64908800-f5968900-d736-11e9-87d0-8828639dc7bd.jpg)

**Comment by melvinzhang** [comment]
Another attempt using gimp to fix the color balance, this one is based on the file in src/images:

![melvin_zhang](https://user-images.githubusercontent.com/1620634/64909200-a6068c00-d73b-11e9-88c3-26933e45aad6.jpg)

Not as good as the one above which a friend of my did for me but still better than the current one.

**Comment by SheldonCheng** [comment]
> Hmm, looks like my gimp-fu is quite terrible and it still looks a bit strange. This is the one I passed to Luther, the colors look more correct but the ratio is different. Please use this instead. Thanks!
> 
> ![melvinz](https://user-images.githubusercontent.com/1620634/64908800-f5968900-d736-11e9-87d0-8828639dc7bd.jpg)

Hey @melvinzhang, just to confirm, this is the one that should be used?

**Comment by melvinzhang** [comment]
It depends on the needs of the site...

If the shape of the image is not an issue, use the square one. It has the better color balance but a different shape than the current one.

If it needs to be the same shape as current image, use the rectangular one. It is the same shape as existing one, with improved color balance.

**Comment by SheldonCheng** [comment]
noted, I've used the the 2nd one that you've provided (rectangular).

**Comment by melvinzhang** [comment]
Awesome, thanks!
